image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Default build cache settings to extend from
.build_cached:
  cache:
    key: "gradle-build"
    paths:
      # Only cache the gradle directory, as we do not use a shared cache
      - .gradle/
    policy: pull

build-submission-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: build
  script:
    gradle submission-microservice:assemble submission-microservice:testClasses

checkStyle-submission-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle submission-microservice:checkstyleMain submission-microservice:checkStyleTest
  allow_failure: true


PMD-submission-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle submission-microservice:pmdMain
  allow_failure: true

test-submission-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: test
  script:
    - gradle submission-microservice:test submission-microservice:jacocoTestReport
    - cat submission-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%" || true
  coverage: /([0-9]{1,3})%/

